
using UnityEngine;
using UnityEngine.UI;
using TMPro;
using System;

/// <summary>
/// Manages the Game Over screen, displaying the final score and providing a restart option.
/// This script was generated by Supreme Guardian Architect v12.
/// </summary>
public class UIPanel_GameOver : UIPanel
{
    [Header("UI Elements")]
    [Tooltip("Text element to display the player's final score.")]
    [SerializeField] private TextMeshProUGUI finalScoreText;

    [Tooltip("Button to restart the game.")]
    [SerializeField] private Button restartButton;

    /// <summary>
    /// Fired when the restart button is clicked.
    /// </summary>
    public event Action OnRestartClicked;

    private void Awake()
    {
        if (restartButton != null)
        {
            restartButton.onClick.AddListener(() => OnRestartClicked?.Invoke());
        }
    }

    /// <summary>
    /// Sets the final score text on the game over screen.
    /// </summary>
    /// <param name="score">The final score to display.</param>
    public void SetFinalScore(int score)
    {
        if (finalScoreText != null)
        {
            finalScoreText.text = "Final Score: " + score.ToString();
        }
    }

    private void OnDestroy()
    {
        if (restartButton != null)
        {
            restartButton.onClick.RemoveAllListeners();
        }
    }
}
