
using TMPro;
using UnityEngine;

/// <summary>
/// Manages the in-game Heads-Up Display (HUD), showing vital player information like score and coins.
/// This script was generated by Supreme Guardian Architect v12.
/// </summary>
public class UIPanel_InGame : UIPanel
{
    [Header("UI Elements")]
    [Tooltip("Text element to display the player's score.")]
    [SerializeField] private TextMeshProUGUI scoreText;

    [Tooltip("Text element to display the player's collected coins.")]
    [SerializeField] private TextMeshProUGUI coinsText;

    /// <summary>
    /// Updates the score display on the HUD.
    /// </summary>
    /// <param name="score">The new score to display.</param>
    public void UpdateScore(int score)
    {
        if (scoreText != null)
        {
            scoreText.text = "Score: " + score.ToString();
        }
    }

    /// <summary>
    /// Updates the coins display on the HUD.
    /// </summary>
    /// <param name="coins">The new coin count to display.</param>
    public void UpdateCoins(int coins)
    {
        if (coinsText != null)
        {
            coinsText.text = "Coins: " + coins.ToString();
        }
    }
}
