using UnityEngine;

namespace EndlessRunner.Procedural
{
    /// <summary>
    /// Defines the structure for a procedural pattern, containing the layout for obstacles and coins.
    /// This data is generated by the ProceduralPatternEngine and consumed by spawning systems.
    /// </summary>
    [System.Serializable]
    public class PatternData
    {
        // Using arrays of booleans to represent slots. True means "place an item here."
        public bool[] ObstacleLayout { get; private set; }
        public bool[] CoinLayout { get; private set; }

        public PatternData(bool[] obstacleLayout, bool[] coinLayout)
        {
            ObstacleLayout = obstacleLayout;
            CoinLayout = coinLayout;
        }
    }
}
